---
apiVersion: v1
kind: Pod
metadata:
  name: sharedvolumeexample
spec:
  containers:
    - name: c1
      image: centos:7
      command:
        - bin/bash
        - -c
        - sleep 10000
      volumeMounts:
        - name: xchange
          mountPath: /tmp/xchange
    - name: c2
      image: centos:7
      command:
        - bin/bash
        - -c
        - sleep 10000
      volumeMounts:
        - name: xchange
          mountPath: /tmp/data
  volumes: null
    - name: xchange
      emptyDir: {}
