apiVersion: v1
kind: Pod
metadata:
  name: DevOps
spec:
    containers:
     - name: c1
       image: centos:7
    command:
     - "bin/bash"
     - "-c"
     - "sleep 10000"
    volumeMounts:
      - name: exchange
        mountPath: "/tmp/exchange"
      - name: c2
        image: centos:7
command:
       - "bin/bash"
       - "-c"
       - "sleep 10000"
volumeMounts:
       - name: exchange
         mountPath: "/tmp/data"
volumes:
        - name: exchange
          emptyDir: {}      
